name: inject
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.0.0-dev.30 <2.0.0'

dependencies:
  analyzer: ^0.31.1
  build: ^0.12.0+2
  code_builder: ^3.0.3
  collection: ^1.14.7
  dart_style: ^1.0.10
  logging: ^0.11.3+1
  meta: ^1.1.2
  path: ^1.5.1
  quiver: ^0.28.0
  stack_trace: ^1.9.2

dev_dependencies:
  test: ^0.12.32+1
